before_script:
  #- apt-get update -qq
  #- apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
deploy_staging:
  stage: deploy
  environment:
    name: Development
    url: 13.127.27.245
  script:
    - ssh ubuntu@13.127.27.245 "cd /var/www/html/nursestaffingsolution/frontend && sudo git checkout development && sudo git pull origin development && sudo /etc/init.d/nginx reload && exit"
  only:
    - development